spes: vintf: Declare Missing mfidoca vendor lib
error: vendor/xiaomi/spes/Android.bp:6444:1: "libmfido" depends on undefined module "vendor.xiaomi.hardware.mfidoca@1.0".
Or did you mean ["libvendorgraphicbuffer_src_defaults" "vendor.xiaomi.hardware.mlipay@1.0" "vendor.xiaomi.hardware.motor@1.0"]?